# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namebrand', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameproduct', models.CharField(max_length=30)),
                ('processor', models.TextField(max_length=30)),
                ('screen_size', models.TextField(max_length=30)),
                ('gpu', models.TextField(max_length=20)),
                ('memory', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('cost', models.IntegerField()),
                ('img', models.ImageField(upload_to='media')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop_El.Brand')),
            ],
        ),
    ]
