# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_El', '0002_auto_20180107_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='idcomputer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='iduser',
        ),
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(to='Shop_El.Profile'),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
