# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop_El', '0004_auto_20180120_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comps',
        ),
        migrations.AddField(
            model_name='product',
            name='comps',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
