# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_El', '0005_auto_20180120_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comps',
            field=models.ManyToManyField(to='Shop_El.Profile'),
        ),
    ]
